name: Build Brunch Image
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y cgpt wget unzip curl

      - name: Pull Framework and Recovery Zip
        run: |
          wget -q https://dl.google.com/dl/edgedl/chromeos/recovery/chromeos_15886.44.0_octopus_recovery_stable-channel_mp-v5.bin.zip
          wget -q https://github.com/sebanc/brunch/releases/download/r126_stable_20240630/brunch_r126_stable_20240630.tar.gz

      - name: Extract Recovery Bin
        run: |
          unzip chromeos_15886.44.0_octopus_recovery_stable-channel_mp-v5.bin.zip
          rm -f chromeos_15886.44.0_octopus_recovery_stable-channel_mp-v5.bin.zip
          tar -zxvf brunch_r126_stable_20240630.tar.gz chromeos-install.sh
          rm -f brunch_r126_stable_20240630.tar.gz

      - name: Compile Final Image (Sparse Mode)
        run: |
          sudo bash chromeos-install.sh -src chromeos_15886.44.0_octopus_recovery_stable-channel_mp-v5.bin -dst ./brunch.img -sparse
          rm -f chromeos_15886.44.0_octopus_recovery_stable-channel_mp-v5.bin

      - name: Compress For Faster Transfer
        run: tar -cvzf brunch_octopus_r126.tar.gz brunch.img

      - name: Upload to High Capacity Cloud Link
        run: |
          echo "=== STARTING STABLE TRANSFER ==="
          curl  https://bashupload.com/brunch_octopus_r126.tar.gz --data-binary @brunch_octopus_r126.tar.gz
